https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.122.146601


In [2]:
import sys
sys.path.insert(0, 'C:/Users/Can/Dropbox/PC (2)/Desktop/My Numerical Calculations/Single Particle/Hofstadter')
from square_tight_binding import *

lx= 4 , ly= 5


In [3]:
p=1
q=L_y #q değeri, ly'nin tam böleni olmak zorunda
#Magnetic Flux Per Plaquet is has to be rational value
alpha=p/q

#Real Space Hamiltonian with Twisted Angle Phases
def HMat_Theta(alpha, theta_x, theta_y):
    H = np.zeros((L_x*L_y, L_x*L_y), dtype=complex)
    for m in range(L_x*L_y):
        for n in range(L_x*L_y):
            #NN
            if m in PerBCLat[n]:
                #X ekseninde sınırdan sınıra atlamalar:
                if np.absolute(xy[m][0]-xy[n][0])==L_x-1:
                    if xy[m][0] > xy[n][0]:
                        H[m][n] = -np.exp(-1j*2*np.pi*(alpha)*xy[m][1])*np.exp(-1j*theta_x)
                    elif xy[m][0] < xy[n][0]:
                        H[m][n] = -np.exp(1j*2*np.pi*(alpha)*xy[m][1])*np.exp(1j*theta_x)

                #Y ekseninde sınırdan sınıra atlamalar
                elif np.absolute(xy[m][1]-xy[n][1])==L_y-1:
                    if xy[m][1] > xy[n][1]:
                        H[m][n] = -np.exp(1j*theta_y)
                    elif xy[m][1] < xy[n][1]:
                        H[m][n] = -np.exp(-1j*theta_y)
                        
                #Lattice içi atlamalar
                else:
                    if xy[m][0] > xy[n][0]:
                        H[m][n] = -np.exp(1j*2*np.pi*alpha*xy[m][1])
                    elif xy[m][0] < xy[n][0]:
                        H[m][n] = -np.exp(-1j*2*np.pi*alpha*xy[m][1])
                    else:
                        H[m][n] = -np.exp(0)
    return H

In [4]:
from Periodic_BC_Hofstadter_Hamiltonian_Matrix import *
PerHMat(alpha) == HMat_Theta(alpha, 0, 0) # check!

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ T

In [12]:
E0, U0 = np.linalg.eig(HMat_Theta(alpha, 9, 9))
#E0 = np.sort(E0)
idx1 = np.argsort(E0)
#U0_sorted = U0[:,idx1]
#E0
idx1

array([ 0,  1,  2,  3,  6, 11, 12, 14, 13, 15, 17, 18, 19, 16, 10,  9,  8,
        7,  5,  4], dtype=int64)

In [23]:
np.sort(np.real(E0))

array([-2.90522026, -2.90522026, -2.90522026, -2.90522026, -2.90522026,
       -1.33468195, -1.33468195, -1.33468195, -1.33468195, -1.33468195,
        0.33808561,  0.33808561,  0.33808561,  0.33808561,  0.33808561,
        0.93800872,  0.93800872,  0.93800872,  0.93800872,  0.93800872,
        2.96380788,  2.96380788,  2.96380788,  2.96380788,  2.96380788])

In [24]:
U0_sorted[:,0]

array([ 0.0009188 -0.00107853j,  0.2358707 -0.04906101j,
        0.22964901-0.07470669j,  0.21094327-0.14387977j,
        0.22248593-0.07447121j, -0.10908309-0.26921512j,
        0.26657993-0.08724305j,  0.04561502+0.06758482j,
        0.0716678 -0.19743766j,  0.32038421+0.j        ,
       -0.10145423-0.26373539j,  0.23789966+0.00503458j,
       -0.09685032+0.1736542j , -0.05155553-0.18928394j,
        0.22591237-0.03336188j, -0.07896817-0.14026833j,
        0.00704807+0.03169849j, -0.06201341+0.11772052j,
        0.00464643-0.04925986j,  0.00400586-0.00107623j,
       -0.10777248-0.12202888j, -0.1798379 +0.05884921j,
       -0.12143736+0.15555405j, -0.05170165+0.10173527j,
       -0.07586961+0.11452455j])

In [25]:
#Twisted Angle Space Doesn't Depend on Lattice Space
theta_size=10
dx = 2*np.pi/theta_size
dy = dx
theta_x = np.arange(0, 2*np.pi, dx)
theta_y = np.arange(0, 2*np.pi, dy)

In [27]:
#Calculate Chern Numbes
chern_array = []
for i in np.arange(0, L_x*L_y, q):
    j=i+q
    S=0
    n1=i
    n2=j
    print(n1,n2)
    for t_x in range(0, len(theta_x)):
        for t_y in range(0, len(theta_y)):
            w1, v1 = np.linalg.eig(HMat_Theta(alpha, theta_x[t_x], theta_y[t_y]))
#             w1 = np.sort(w1)
            idx1 = np.argsort(w1)
            v1_sorted = v1[:,idx1]
            v11 = v1_sorted[:,n1:n2] #multiplet 
            w2, v2 = np.linalg.eig(HMat_Theta(alpha, theta_x[t_x]+dx, theta_y[t_y]))
#             w2 = np.sort(w2)
            idx2 = np.argsort(w2)
            v2_sorted = v2[:,idx2]
            v22 = v2_sorted[:,n1:n2]
            w3, v3 = np.linalg.eig(HMat_Theta(alpha, theta_x[t_x], theta_y[t_y]+dy))
#             w3 = np.sort(w3)
            idx3 = np.argsort(w3)
            v3_sorted = v3[:,idx3]
            v33 = v3_sorted[:,n1:n2]
            w4, v4 = np.linalg.eig(HMat_Theta(alpha, theta_x[t_x]+dx, theta_y[t_y]+dy))
#             w4 = np.sort(w4)
            idx4 = np.argsort(w4)
            v4_sorted = v4[:,idx4]
            v44 = v4_sorted[:,n1:n2]
            # CHECK: 
            # v11,v22,v33,v44 D-Fold Degenerate Multiplet Matrices (w1,w2,w3,w4 are degenerate)
            U1 = np.linalg.det(np.matmul(np.conjugate(np.transpose(v11)), v22)) #U_x
            U1 = U1 / np.absolute(U1)
            U2 = np.linalg.det(np.matmul(np.conjugate(np.transpose(v22)), v44)) #U_y dx
            U2 = U2 / np.absolute(U2)
            U3 = np.linalg.det(np.matmul(np.conjugate(np.transpose(v33)), v44)) #U_x dy
            U3 = U3 / np.absolute(U3)
            U4 = np.linalg.det(np.matmul(np.conjugate(np.transpose(v11)), v33)) #U_y
            U4 = U4 / np.absolute(U4)
            F = np.log(U1*U2*1/U3*1/U4)
            S = S+F

    C = 1/(2*np.pi*1j)*S
    C.real
    chern_array.append(C.real)
#Chern_Numbers = np.array(chern_array)
print('Chern Numbers (q='+str(q)+') of Seperation of Bands: '+str(chern_array))

0 5
5 10
10 15
15 20
20 25
Chern Numbers (q=5) of Seperation of Bands: [0.9999999999999999, 1.0000000000000002, -4.000000000000001, 0.9999999999999996, 0.9999999999999998]


# SORU:

Neden E'leri küçükten büyüğe sıraladığımda Chern'ler değişti?

"Hofstadter SP Chern Numbers in Julia" dosyası ile E'ler ve E'lerin sırası aynı olduğu halde neden U'ların sırası aynı değil?

MB Hofstadter Chern Hesabı tutarsızlığı buradan kaynaklanıyor olabilir.

# Problem Dışı:

Dejenere enerjilere karşılık gelen tam öz-değerleri almıyoruz. Örneğin, lx=ly=5 iken 5'er kat dejenere gelen enerjileri 6'şar 6'şar multipler şeklinde aldığımız da Chern'ler doğru üretiliyor.