https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.122.146601


In [8]:
import sys

In [9]:
L_x = 3
L_y = 3
p = 1
q = L_y

In [10]:
sys.path.insert(0, '../')
from square_tight_binding import *

In [11]:
# Discreatizing Brillioun Zone / Theta Space
Nt1=10
Nt2=10
dx = 2*np.pi/Nt1
dy = dx
theta_x = np.arange(0, 2*np.pi, dx)
theta_y = np.arange(0, 2*np.pi, dy)

# Comparison of The Two Hamiltonians

In [12]:
HHp = HMat_Theta(L_x, L_y, p, q, theta_x[1], theta_y[2])

In [13]:
HHj = np.load("../../../Single Particle/HHj.npy")

In [14]:
HHj == HHp

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

Hamiltonyeninlerin tam olarak aynı gelmesi için, "Lattice_Basis_Neighbors_hops.ipynb" dosyasında get_Hofstadter_hop() fonksiyonu içerisinde ki "*exp(-1im*param_dict["θθ"][2]*wraps[2])" kısmı negatif olmalı. Ancak bu terimin negatif gelmesi, yani düşey yöndeki sınırdan sınıra olan atlamalardaki yönün ters seçilmesi, Chern hesabından bir etkiye sahip değildir!

# Comparison of The Two Eigen States

In [15]:
sys.path.insert(0, '../../')
from Chern_parameter_space_sum import *

In [16]:
EEA, UUAp = calc_states_twist_hofstadter(L_x, L_y, Nt1, Nt2, p, q, theta_x, theta_y, HMat_Theta)
UUp = calc_link_vars_twist(UUAp[:,:,:,0:3])
F12p = calc_F12_BZ(UUp)

In [17]:
np.save("UUAp.npy", UUAp)

In [221]:
UU[0,0,:]

array([-0.69267219-0.72125255j,  0.99739738-0.07210042j])

In [222]:
np.log(UU[0,0,0]*UU[1,0,1]/UU[0,1,0]/UU[0,0,1])

(-4.0969289592796e-17+0.007370547610764475j)

In [226]:
F12p[0,0]

(6.990054693921388e-17+0.0073705476107644545j)

In [223]:
EEA, UUA = calc_states_twist_hofstadter(L_x, L_y, Nt1, Nt2, p, q, theta_x, theta_y, HMat_Theta)
for i in np.arange(0, L_x*L_y, q):
    j=i+q
    n1=i
    n2=j
    UU = calc_link_vars_twist(UUA[:,:,:,i:j])
    F12 = calc_F12_BZ(UU)
    print(f'{F12.sum()/(2j*np.pi):.2e}')

1.00e+00+1.38e-16j
-2.00e+00+8.14e-18j
1.00e+00-8.97e-16j


In [196]:
EEA[2,1,:]

array([-2.61803399, -2.61803399, -2.61803399,  0.38196601,  0.38196601,
        0.38196601,  2.23606798,  2.23606798,  2.23606798])

In [210]:
calc_link_var_twist(UUA[0,0,:,0:3], UUA[1,0,:,0:3])

(-0.6926721895662789-0.7212525478647941j)

In [198]:
calc_link_vars_twist(UUA)[8,0,:]

array([-0.49274687-0.8701727j ,  0.08543995-0.99634332j])

In [184]:
UUAj = np.load("../../../Many-Body/Hofstadter/UUAj.npy")

In [185]:
inner = np.conj(np.transpose(UUAj[2,1,:,:]))@UUA[2,1,:,:]
np.isclose(inner,np.zeros([9,9]))

array([[False, False, False,  True,  True,  True,  True,  True,  True],
       [False, False, False,  True,  True,  True,  True,  True,  True],
       [False, False, False,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True, False, False, False,  True,  True,  True],
       [ True,  True,  True, False, False, False,  True,  True,  True],
       [ True,  True,  True, False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True, False, False, False],
       [ True,  True,  True,  True,  True,  True, False, False, False],
       [ True,  True,  True,  True,  True,  True, False, False, False]])

In [186]:
innerp = np.conj(np.transpose(UUA[2,1,:,:]))@UUA[2,1,:,:]
innerp == np.identity(9)
np.isclose(innerp, np.identity(9))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [187]:
innerj = np.conj(np.transpose(UUAj[2,1,:,:]))@UUAj[2,1,:,:]
innerj == np.identity(9)
np.isclose(innerj, np.identity(9))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [188]:
F12j = np.load("../../../Many-Body/Hofstadter/F12j.npy")

In [192]:
F12p

array([[ 1.11022302e-16-0.47183882j, -3.05311332e-16-0.42511656j,
        -2.49800181e-16+0.74425577j, -2.77555756e-17+0.54446735j,
        -2.35922393e-16-1.51685341j, -1.17961196e-16+1.77933209j,
        -3.15502832e-17+1.53579245j,  2.77555756e-17-0.65269483j,
         2.91433544e-16+2.06810515j,  1.38777878e-16-1.16282548j],
       [-5.55111512e-17+0.99960992j, -3.19189120e-16-0.47014833j,
        -1.04083409e-17-1.8173553j ,  1.52655666e-16-1.41954666j,
        -3.29597460e-16-1.39031748j, -3.29597460e-16+1.4532128j ,
        -2.49800181e-16+0.84640488j,  2.22044605e-16+0.63271024j,
        -2.62810607e-16+3.0361254j , -2.77555756e-16-2.70271307j],
       [ 2.84494650e-16-0.19146065j, -2.77555756e-17-0.72082383j,
         0.00000000e+00-2.76650383j,  2.77555756e-17+1.33629735j,
        -6.93889390e-17-2.01584355j,  7.45931095e-17-0.17448773j,
         3.90529623e-16-1.62884447j, -1.11022302e-16+2.12180989j,
        -3.14093369e-16-3.10067876j, -1.34441069e-17-1.65446947j],
       

In [150]:
np.abs(F12j)

array([[0.83548933, 1.23587456, 2.11092565, 1.58319864, 0.28199738,
        0.87707272, 1.85818776, 2.71047512, 1.00876023, 0.85211589],
       [0.91302159, 3.50014353, 1.65511088, 1.50852832, 1.59232333,
        0.98841725, 1.08646335, 1.56064799, 2.46560174, 1.34431576],
       [1.07492403, 0.78800875, 2.04630144, 0.2030705 , 1.72619845,
        1.60752593, 2.11672625, 0.63991994, 1.27080039, 0.59030257],
       [1.17018347, 4.54530449, 2.65010634, 1.55302228, 2.43100062,
        1.79319415, 2.09183385, 1.64227848, 3.50442423, 1.05413318],
       [1.60361069, 1.9999104 , 2.39172366, 0.10679518, 2.76534671,
        0.04467579, 2.63850012, 0.83978118, 1.30997971, 0.66440628],
       [3.10483598, 6.62688456, 4.55757517, 1.09878281, 5.0439466 ,
        1.974429  , 4.50343905, 2.02559303, 5.23957265, 0.86065929],
       [2.44780046, 4.27120732, 2.66133773, 0.68316518, 3.25455215,
        1.00527905, 3.57352914, 2.0408909 , 2.74016684, 0.67136912],
       [1.33092795, 1.36225319, 1.4896599