In [2]:
using QuantumOptics
using Einsum

In [128]:
basis = NLevelBasis(2) 

NLevel(N=2)

In [129]:
t = -1

H1 = t * ( transition(basis,1,2) + transition(basis,2,1) )

Operator(dim=2x2)
  basis: NLevel(N=2)sparse([2, 1], [1, 2], ComplexF64[-1.0 - 0.0im, -1.0 - 0.0im], 2, 2)

In [130]:
E1, U1 = eigenstates(dense(H1))

([-1.0, 1.0], Ket{NLevelBasis{Int64}, Vector{ComplexF64}}[Ket(dim=2)
  basis: NLevel(N=2)
 -0.7071067811865475 + 0.0im
 -0.7071067811865475 + 0.0im, Ket(dim=2)
  basis: NLevel(N=2)
 -0.7071067811865475 + 0.0im
  0.7071067811865475 + 0.0im])

In [131]:
# projection
substates = 1:1
basis_tilde = SubspaceBasis(basis, U1[substates])

Subspace(superbasis=NLevel(N=2), states:1)

In [132]:
projector(basis_tilde, basis)

Operator(dim=1x2)
  basis left:  Subspace(superbasis=NLevel(N=2), states:1)
  basis right: NLevel(N=2)
 -0.707107-0.0im  -0.707107-0.0im

In [133]:
projector(basis, basis_tilde)

Operator(dim=2x1)
  basis left:  NLevel(N=2)
  basis right: Subspace(superbasis=NLevel(N=2), states:1)
 -0.707107+0.0im
 -0.707107+0.0im

In [134]:
P1 = projector(basis, basis_tilde)
P1_dag = dagger(P1)

Operator(dim=1x2)
  basis left:  Subspace(superbasis=NLevel(N=2), states:1)
  basis right: NLevel(N=2)
 -0.707107-0.0im  -0.707107-0.0im

In [135]:
ψ = 3//5*nlevelstate(basis,1) + 4//5*nlevelstate(basis,2)

Ket(dim=2)
  basis: NLevel(N=2)
 0.6 + 0.0im
 0.8 + 0.0im

In [136]:
ψ = Ket(basis, [3//5,4//5])

Ket(dim=2)
  basis: NLevel(N=2)
 0.6
 0.8

In [137]:
P1_dag*ψ

Ket(dim=1)
  basis: Subspace(superbasis=NLevel(N=2), states:1)
 -0.9899494936611664 + 0.0im

In [138]:
H1_sub = P1_dag*H1*P1

Operator(dim=1x1)
  basis: Subspace(superbasis=NLevel(N=2), states:1)
 -1.0+0.0im

# Many-body

In [139]:
# many-body basis
PN = 2 
states_mb = bosonstates(basis, PN)

3-element QuantumOpticsBase.SortedVector{Vector{Int64}, Base.Order.ReverseOrdering{Base.Order.ForwardOrdering}}:
 [2, 0]
 [1, 1]
 [0, 2]

In [140]:
basis_mb = ManyBodyBasis(basis, states_mb)

ManyBody(onebodybasis=NLevel(N=2), states:3)

In [141]:
H1_mb = manybodyoperator(basis_mb, H1)

Operator(dim=3x3)
  basis: ManyBody(onebodybasis=NLevel(N=2), states:3)sparse([2, 1, 3, 2], [1, 2, 2, 3], ComplexF64[-1.4142135623730951 - 0.0im, -1.4142135623730951 - 0.0im, -1.4142135623730951 - 0.0im, -1.4142135623730951 - 0.0im], 3, 3)

In [142]:
# Hubbard interaction
U0 = 0.1
n1 = number(basis_mb, 1)
n2 = number(basis_mb, 2)
Id = identityoperator(basis_mb)
Vint_mb = U0/2*(n1*(n1-Id) + n2*(n2-Id))

Operator(dim=3x3)
  basis: ManyBody(onebodybasis=NLevel(N=2), states:3)sparse([1, 3], [1, 3], ComplexF64[0.1 + 0.0im, 0.1 + 0.0im], 3, 3)

In [143]:
H_mb = H1_mb + Vint_mb

Operator(dim=3x3)
  basis: ManyBody(onebodybasis=NLevel(N=2), states:3)sparse([1, 2, 1, 3, 2, 3], [1, 1, 2, 2, 3, 3], ComplexF64[0.1 + 0.0im, -1.4142135623730951 + 0.0im, -1.4142135623730951 + 0.0im, -1.4142135623730951 + 0.0im, -1.4142135623730951 + 0.0im, 0.1 + 0.0im], 3, 3)

In [144]:
dense( H_mb )

Operator(dim=3x3)
  basis: ManyBody(onebodybasis=NLevel(N=2), states:3)
      0.1+0.0im  -1.41421+0.0im       0.0+0.0im
 -1.41421+0.0im       0.0+0.0im  -1.41421+0.0im
      0.0+0.0im  -1.41421+0.0im       0.1+0.0im

In [145]:
eigenenergies( dense(H_mb) )

3-element Vector{Float64}:
 -1.9506249023742561
  0.09999999999999994
  2.0506249023742558

In [146]:
EE, UU = eigenstates( H_mb, 3)

[ Info: Defaulting to sparse diagonalization for sparse operator. If storing the full operator is possible, it might be faster to do `eigenstates(dense(op))`. Set `info=false` to turn off this message.


([-1.9506249023742543, 0.10000000000000275, 2.0506249023742558], Ket{ManyBodyBasis{NLevelBasis{Int64}, QuantumOpticsBase.SortedVector{Vector{Int64}, Base.Order.ReverseOrdering{Base.Order.ForwardOrdering}}, UInt64}, Vector{ComplexF64}}[Ket(dim=3)
  basis: ManyBody(onebodybasis=NLevel(N=2), states:3)
 0.37121179125734394 + 0.3255053889591743im
  0.5382610968105257 + 0.47198632103105626im
 0.37121179125734366 + 0.3255053889591746im, Ket(dim=3)
  basis: ManyBody(onebodybasis=NLevel(N=2), states:3)
 -0.5294862362395769 + 0.4686622724658417im
             1.4e-16 + 3.0e-17im
   0.529486236239577 - 0.46866227246584147im, Ket(dim=3)
  basis: ManyBody(onebodybasis=NLevel(N=2), states:3)
 -0.23212277546447876 + 0.44985227008510026im
   0.3201669664866272 - 0.6204812793232759im
 -0.23212277546447885 + 0.44985227008510026im])

In [147]:
# alternatively construct Vint from the 2-body matrix elements
# transition(basis,i,k)⊗transition(basis,j,l) goes with V_ijkl 

In [148]:
V2  = U0/2*transition(basis,1,1)⊗transition(basis,1,1) 
V2 += U0/2*transition(basis,2,2)⊗transition(basis,2,2) 

Operator(dim=4x4)
  basis: [NLevel(N=2) ⊗ NLevel(N=2)]sparse([1, 4], [1, 4], ComplexF64[0.05 + 0.0im, 0.05 + 0.0im], 4, 4)

In [149]:
V2.data

4×4 SparseArrays.SparseMatrixCSC{ComplexF64, Int64} with 2 stored entries:
 0.05+0.0im      ⋅          ⋅           ⋅    
      ⋅          ⋅          ⋅           ⋅    
      ⋅          ⋅          ⋅           ⋅    
      ⋅          ⋅          ⋅      0.05+0.0im

In [150]:
V2_mb = manybodyoperator(basis_mb, V2)

Operator(dim=3x3)
  basis: ManyBody(onebodybasis=NLevel(N=2), states:3)sparse([1, 3], [1, 3], ComplexF64[0.1 + 0.0im, 0.1 + 0.0im], 3, 3)

In [151]:
isapprox(V2_mb, Vint_mb)

true

In [152]:
# compare the following for indexing the 2-ptl states
transition(basis,1,2)⊗transition(basis,1,1), transition(basis,1,1)⊗transition(basis,1,2)

(Operator(dim=4x4)
  basis: [NLevel(N=2) ⊗ NLevel(N=2)]sparse([1], [2], ComplexF64[1.0 + 0.0im], 4, 4), Operator(dim=4x4)
  basis: [NLevel(N=2) ⊗ NLevel(N=2)]sparse([1], [3], ComplexF64[1.0 + 0.0im], 4, 4))

In [153]:
P1M = P1.data
P1_dagM = P1_dag.data

1×2 adjoint(::Matrix{ComplexF64}) with eltype ComplexF64:
 -0.707107-0.0im  -0.707107-0.0im

In [154]:
H1M = H1.data

2×2 SparseArrays.SparseMatrixCSC{ComplexF64, Int64} with 2 stored entries:
      ⋅      -1.0-0.0im
 -1.0-0.0im       ⋅    

In [155]:
V2M = V2.data

4×4 SparseArrays.SparseMatrixCSC{ComplexF64, Int64} with 2 stored entries:
 0.05+0.0im      ⋅          ⋅           ⋅    
      ⋅          ⋅          ⋅           ⋅    
      ⋅          ⋅          ⋅           ⋅    
      ⋅          ⋅          ⋅      0.05+0.0im

In [156]:
P2M = (P1⊗P1).data
P2_dagM = (P1_dag⊗P1_dag).data

1×4 Matrix{ComplexF64}:
 0.5+0.0im  0.5+0.0im  0.5+0.0im  0.5+0.0im

In [157]:
@einsum H1_tildeM[i,j] := P1_dagM[i,k] * H1M[k,l] * P1M[l,j];
@einsum V2_tildeM[i2,j2] :=  P2_dagM[i2,k2] * V2M[k2,l2] * P2M[l2,j2];
@einsum U4[k,l,m,n] := P1M[k,i] * P1M[l,i] * P1_dagM[i,m] * P1_dagM[i,n];

In [158]:
H1_tilde = Operator(basis_tilde, H1_tildeM)

Operator(dim=1x1)
  basis: Subspace(superbasis=NLevel(N=2), states:1)
 -1.0+0.0im

In [161]:
states_mb_tilde = bosonstates(basis_tilde, PN)

basis_mb_tilde  = ManyBodyBasis(basis_tilde, states_mb_tilde)

ManyBody(onebodybasis=Subspace(superbasis=NLevel(N=2), states:1), states:1)

In [162]:
H_NI_tilde = manybodyoperator(basis_mb_tilde, H1_tilde)

Operator(dim=1x1)
  basis: ManyBody(onebodybasis=Subspace(superbasis=NLevel(N=2), states:1), states:1)
 -2.0+0.0im

In [163]:
basis_tilde2 = basis_tilde⊗basis_tilde

[Subspace(superbasis=NLevel(N=2), states:1) ⊗ Subspace(superbasis=NLevel(N=2), states:1)]

In [173]:
Vint_tilde = Operator(basis_tilde2, U0/2*reshape(U4,4,4))

LoadError: DimensionMismatch: Tried to assign data of size (4, 4) to bases of length 1 and 1!

In [174]:
V2_tilde = Operator(basis_tilde2, V2_tildeM)

Operator(dim=1x1)
  basis: [Subspace(superbasis=NLevel(N=2), states:1) ⊗ Subspace(superbasis=NLevel(N=2), states:1)]
 0.025+0.0im

In [175]:
isapprox(Vint_tilde, V2_tilde)

false

In [176]:
Vint_tilde_mb = manybodyoperator(basis_mb_tilde, Vint_tilde)

LoadError: ArgumentError: The basis of the given operator has to either be equal to b or b ⊗ b where b is the 1st quantization basis associated to the nparticle basis.

In [177]:
Vint_tilde_mb = manybodyoperator(basis_mb_tilde, V2_tilde)

Operator(dim=1x1)
  basis: ManyBody(onebodybasis=Subspace(superbasis=NLevel(N=2), states:1), states:1)
 0.05+0.0im

In [178]:
H_mb_tilde = H_NI_tilde + Vint_tilde_mb

Operator(dim=1x1)
  basis: ManyBody(onebodybasis=Subspace(superbasis=NLevel(N=2), states:1), states:1)
 -1.95+0.0im

In [179]:
eigenenergies( dense(H_mb_tilde) )

1-element Vector{Float64}:
 -1.9499999999999995

In [180]:
EEt, UUt = eigenstates(  H_mb_tilde )

([-1.9499999999999995], Ket{ManyBodyBasis{SubspaceBasis{Vector{Int64}, NLevelBasis{Int64}, Ket{NLevelBasis{Int64}, Vector{ComplexF64}}, 0x78c50465b7827ef8, UInt64}, QuantumOpticsBase.SortedVector{Vector{Int64}, Base.Order.ReverseOrdering{Base.Order.ForwardOrdering}}, UInt64}, Vector{ComplexF64}}[Ket(dim=1)
  basis: ManyBody(onebodybasis=Subspace(superbasis=NLevel(N=2), states:1), states:1)
 1.0 + 0.0im])

In [181]:
states_mb

3-element QuantumOpticsBase.SortedVector{Vector{Int64}, Base.Order.ReverseOrdering{Base.Order.ForwardOrdering}}:
 [2, 0]
 [1, 1]
 [0, 2]

In [182]:
state_list = []
for state in states_mb
    #println(findall(state.!=0))
    repr = Int64[]
    for oi in findall(state.!=0)
            push!(repr,repeat([oi],state[oi])...)
    end
    #println(repr)
    push!(state_list, repr)
end
state_list

3-element Vector{Any}:
 [1, 1]
 [1, 2]
 [2, 2]

In [183]:
state_index = Dict()
for (ind, state) in enumerate(state_list)
    state_index[state] = ind
end
state_index

Dict{Any, Any} with 3 entries:
  [1, 1] => 1
  [2, 2] => 3
  [1, 2] => 2

In [184]:
using Combinatorics

In [185]:
Set( collect(permutations(state_list[2])) )

Set{Vector{Int64}} with 2 elements:
  [2, 1]
  [1, 2]

In [186]:
basis_mb.shape

3

In [204]:
PMB = zeros(ComplexF64,basis_mb.shape,basis_mb_tilde.shape)
for iMB in 1:basis_mb.shape
    i_occ_lists = Set( collect(permutations(state_list[iMB])) )
    ilistlen = length(i_occ_lists)
    for jMB in 1:basis_mb_tilde.shape
        j_occ_lists = Set( collect(permutations(state_list[jMB])) )
        jlistlen = length(j_occ_lists)
        for (iocc_ind,iocc) in enumerate(i_occ_lists)
            for (jocc_ind,jocc) in enumerate(j_occ_lists)
                P1val=1
                for ind in 1:PN
                    P1val *= P1M[iocc[ind],jocc[ind]]
                    println(iMB,'\t',jMB,'\t', iocc_ind,jocc_ind, '\t', P1val)
                end    
                PMB[iMB,jMB] += P1val/sqrt(ilistlen*jlistlen) 
            end
        end
    end
end

1	1	11	-0.7071067811865475 + 0.0im
1	1	11	0.4999999999999999 - 0.0im
2	1	11	-0.7071067811865475 + 0.0im
2	1	11	0.4999999999999999 - 0.0im
2	1	21	-0.7071067811865475 + 0.0im
2	1	21	0.4999999999999999 - 0.0im
3	1	11	-0.7071067811865475 + 0.0im
3	1	11	0.4999999999999999 - 0.0im


In [205]:
P1M

2×1 Matrix{ComplexF64}:
 -0.7071067811865475 + 0.0im
 -0.7071067811865475 + 0.0im

In [206]:
PMB

3×1 Matrix{ComplexF64}:
 0.4999999999999999 + 0.0im
 0.7071067811865474 + 0.0im
 0.4999999999999999 + 0.0im

In [207]:
UU

3-element Vector{Ket{ManyBodyBasis{NLevelBasis{Int64}, QuantumOpticsBase.SortedVector{Vector{Int64}, Base.Order.ReverseOrdering{Base.Order.ForwardOrdering}}, UInt64}, Vector{ComplexF64}}}:
 Ket(dim=3)
  basis: ManyBody(onebodybasis=NLevel(N=2), states:3)
 0.37121179125734394 + 0.3255053889591743im
  0.5382610968105257 + 0.47198632103105626im
 0.37121179125734366 + 0.3255053889591746im
 Ket(dim=3)
  basis: ManyBody(onebodybasis=NLevel(N=2), states:3)
 -0.5294862362395769 + 0.4686622724658417im
             1.4e-16 + 3.0e-17im
   0.529486236239577 - 0.46866227246584147im
 Ket(dim=3)
  basis: ManyBody(onebodybasis=NLevel(N=2), states:3)
 -0.23212277546447876 + 0.44985227008510026im
   0.3201669664866272 - 0.6204812793232759im
 -0.23212277546447885 + 0.44985227008510026im

In [208]:
PMB'*UU[1].data

1-element Vector{ComplexF64}:
 0.751819862860975 + 0.659250117187525im

In [209]:
UUt

1-element Vector{Ket{ManyBodyBasis{SubspaceBasis{Vector{Int64}, NLevelBasis{Int64}, Ket{NLevelBasis{Int64}, Vector{ComplexF64}}, 0x78c50465b7827ef8, UInt64}, QuantumOpticsBase.SortedVector{Vector{Int64}, Base.Order.ReverseOrdering{Base.Order.ForwardOrdering}}, UInt64}, Vector{ComplexF64}}}:
 Ket(dim=1)
  basis: ManyBody(onebodybasis=Subspace(superbasis=NLevel(N=2), states:1), states:1)
 1.0 + 0.0im

In [210]:
PMB

3×1 Matrix{ComplexF64}:
 0.4999999999999999 + 0.0im
 0.7071067811865474 + 0.0im
 0.4999999999999999 + 0.0im

In [211]:
for iMB in 1:basis_mb.shape
    println( norm( UU[iMB]'*Operator(basis_mb,basis_mb_tilde,PMB)*UUt[iMB] ))
end

0.9999219085528933


LoadError: BoundsError: attempt to access 1-element Vector{Ket{ManyBodyBasis{SubspaceBasis{Vector{Int64}, NLevelBasis{Int64}, Ket{NLevelBasis{Int64}, Vector{ComplexF64}}, 0x78c50465b7827ef8, UInt64}, QuantumOpticsBase.SortedVector{Vector{Int64}, Base.Order.ReverseOrdering{Base.Order.ForwardOrdering}}, UInt64}, Vector{ComplexF64}}} at index [2]

In [58]:
basis_mb.onebodybasis

NLevel(N=2)

In [59]:
basis_mb_tilde.onebodybasis.basisstates

2-element Vector{Ket{NLevelBasis{Int64}, Vector{ComplexF64}}}:
 Ket(dim=2)
  basis: NLevel(N=2)
 -0.7071067811865475 + 0.0im
 -0.7071067811865475 + 0.0im
 Ket(dim=2)
  basis: NLevel(N=2)
 -0.7071067811865475 + 0.0im
  0.7071067811865475 + 0.0im

In [125]:
H_mb_tilde

Operator(dim=3x3)
  basis: ManyBody(onebodybasis=Subspace(superbasis=NLevel(N=2), states:2), states:3)
 -1.95+0.0im  0.0+0.0im  0.05+0.0im
   0.0+0.0im  0.1+0.0im   0.0+0.0im
  0.05+0.0im  0.0+0.0im  2.05+0.0im

In [126]:
Proj_MB = Operator(basis_mb,basis_mb_tilde,PMB)

Operator(dim=3x3)
  basis left:  ManyBody(onebodybasis=NLevel(N=2), states:3)
  basis right: ManyBody(onebodybasis=Subspace(superbasis=NLevel(N=2), states:2), states:3)
      0.5+0.0im   0.707107+0.0im        0.5+0.0im
 0.707107+0.0im        0.0+0.0im  -0.707107+0.0im
      0.5+0.0im  -0.707107+0.0im        0.5+0.0im

In [127]:
Proj_MB'*H_mb*Proj_MB

Operator(dim=3x3)
  basis: ManyBody(onebodybasis=Subspace(superbasis=NLevel(N=2), states:2), states:3)
 -1.95+0.0im  0.0+0.0im  0.05+0.0im
   0.0+0.0im  0.1+0.0im   0.0+0.0im
  0.05+0.0im  0.0+0.0im  2.05+0.0im